name: scoped
description: A simple dependency injection library built on Zones
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.6


dependencies:
  meta: ^1.12.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.24.0
  very_good_analysis: ^5.1.0
